---
abstract: "Load YAML from URI file\r"
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::MockModule: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-LoadURI
no_index:
  directory:
    - inc
    - t
requires:
  LWP::Simple: 0
  YAML::Any: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
